name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Liberica JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Build and Test with Maven
        run: mvn clean test

      - name: Upload Test Report
        uses: actions/upload-artifact@v3.2.5
        with:
          name: surefire-reports
          path: target/surefire-reports
