name: Cucumber BDD Test Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Liberica JDK 17.0.14
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.14'
          distribution: 'liberica'
          cache: maven

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Build and test with Maven
        run: mvn clean test -Dcucumber.options="--tags @SmokeTest"

      - name: Generate Cucumber Reports
        if: always()
        run: mvn verify

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: cucumber-reports
          path: target/cucumber-reports/

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'