name: Java CI with Liberica

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Liberica JDK 17.0.14
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: 17.0.14

      - name: Build with Maven
        run: mvn clean install
